#!/usr/bin/env python3
"""Remove marked generated files within an explicitly selected workspace subtree."""

import os
import re
from pathlib import Path

workspace = Path(os.environ["GITHUB_WORKSPACE"]).resolve()
target = (workspace / os.environ["WORKING_DIRECTORY"]).resolve()
if target == workspace or not target.is_relative_to(workspace):
    raise SystemExit("Select a directory strictly inside GITHUB_WORKSPACE")

if not target.is_dir():
    raise SystemExit(f"Directory does not exist: {target}")

for directory, _children, files in os.walk(target, topdown=False, followlinks=False):
    for name in files:
        path = Path(directory) / name
        if path.is_symlink():
            continue

        with path.open("rb") as source:
            header = b"".join(source.readline() for _ in range(10)).lower()

        if re.search(rb"generated by[^\r\n]*do not edit", header):
            print(f"Removing generated file: {path.relative_to(workspace)}")
            path.unlink()

    path = Path(directory)
    if path != target and not any(path.iterdir()):
        path.rmdir()
