import json
import os
import subprocess
import tempfile
import unittest
from datetime import UTC, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACTIONS = ROOT / ".github/actions"


class SupportTests(unittest.TestCase):
    def test_cloud_credentials_leave_the_build_workspace(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            workspace = root / "workspace"
            workspace.mkdir()
            temporary = root / "runner-temp"
            temporary.mkdir()
            source = workspace / "gha-creds-fixture.json"
            source.write_text('{"fixture": true}')
            output = root / "output"
            environment = root / "environment"
            subprocess.run(
                ["python3", ACTIONS / "gcp-gar-auth/isolate-credentials.py"],
                env={
                    **os.environ,
                    "CREDENTIALS_FILE": str(source),
                    "RUNNER_TEMP": str(temporary),
                    "GITHUB_OUTPUT": str(output),
                    "GITHUB_ENV": str(environment),
                },
                check=True,
            )
            destination = Path(output.read_text().strip().removeprefix("path="))
            self.assertFalse(source.exists())
            self.assertTrue(destination.is_relative_to(temporary))
            self.assertEqual(destination.stat().st_mode & 0o777, 0o600)
            self.assertIn(f"GOOGLE_APPLICATION_CREDENTIALS={destination}", environment.read_text())

    def test_cleaner_preserves_handwritten_files_and_symlinks(self):
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory)
            target = workspace / "generated"
            target.mkdir()
            (target / "generated.go").write_text("// Generated by test; DO NOT EDIT.\n")
            (target / "manual.go").write_text("// Handwritten\n")
            outside = workspace / "outside.go"
            outside.write_text("// Generated by test; DO NOT EDIT.\n")
            (target / "linked.go").symlink_to(outside)
            env = {**os.environ, "GITHUB_WORKSPACE": directory, "WORKING_DIRECTORY": "generated"}
            subprocess.run(
                ["python3", ACTIONS / "clean-generated-output-dir/clean.py"],
                env=env,
                check=True,
                capture_output=True,
            )
            self.assertFalse((target / "generated.go").exists())
            self.assertTrue((target / "manual.go").exists())
            self.assertTrue(outside.exists())
            env["WORKING_DIRECTORY"] = "."
            result = subprocess.run(
                ["python3", ACTIONS / "clean-generated-output-dir/clean.py"],
                env=env,
                capture_output=True,
            )
            self.assertNotEqual(result.returncode, 0)

    def test_custom_cache_destination_does_not_discard_default_source(self):
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "output"
            env = {
                **os.environ,
                "GITHUB_OUTPUT": str(output),
                "REPO": "example/project",
                "CACHE_FROM": "",
                "CACHE_TO": "type=local,dest=/tmp/cache",
                "GITHUB_REF_NAME": "main",
                "GITHUB_EVENT_NAME": "push",
            }
            subprocess.run(
                ["bash", ACTIONS / "docker-publish-core/scripts/resolve-cache.sh"],
                env=env,
                check=True,
            )
            contents = output.read_text()
            self.assertIn("type=gha,scope=example-project-branch-main", contents)
            self.assertIn("type=local,dest=/tmp/cache", contents)

    def test_cleanup_dry_run_warning_and_deletion_boundaries(self):
        with tempfile.TemporaryDirectory() as directory:
            temp = Path(directory)
            executable = temp / "gh"
            executable.write_text("""#!/usr/bin/env python3
import json, os, sys
from pathlib import Path
from urllib.parse import unquote
fixture = json.loads(Path(os.environ['FIXTURE']).read_text())
endpoint = sys.argv[2]
method = sys.argv[sys.argv.index('--method') + 1]
body = json.load(sys.stdin) if '--input' in sys.argv else None
if method != 'GET' and endpoint != 'graphql':
    with open(os.environ['MUTATIONS'], 'a') as log:
        log.write(json.dumps({'endpoint': endpoint, 'method': method, 'body': body}) + '\\n')
if endpoint == 'graphql': result = {'data': {'viewer': {'login': 'ci[bot]'}}}
elif endpoint == 'repos/example/project': result = {'default_branch': 'main'}
elif '/issues?' in endpoint: result = fixture['issues']
elif '/branches?' in endpoint: result = fixture['branches']
elif '/branches/' in endpoint:
    result = {'protected': False, 'commit': {'sha': fixture.get('current_sha', 'old')}}
elif '/commits/' in endpoint:
    result = {'commit': {'committer': {'date': fixture['date']}}}
elif '/pulls?' in endpoint:
    result = [{}] if unquote(endpoint).endswith(':has-pr') else []
else: result = {}
print(json.dumps([result] if '--slurp' in sys.argv else result))
""")
            executable.chmod(0o755)
            old = (datetime.now(UTC) - timedelta(days=60)).isoformat()
            warning = {"sha": "old", "warned_at": old}
            fixture = {
                "branches": [
                    {"name": name, "protected": name == "protected", "commit": {"sha": "old"}}
                    for name in ["main", "protected", "has-pr", "stale"]
                ],
                "issues": [],
                "date": old,
            }
            fixture_path = temp / "fixture.json"
            mutations = temp / "mutations.jsonl"
            env = {
                **os.environ,
                "PATH": str(temp) + os.pathsep + os.environ["PATH"],
                "FIXTURE": str(fixture_path),
                "MUTATIONS": str(mutations),
                "REPOSITORIES": "example/project",
                "DRY_RUN": "true",
                "STALE_DAYS": "30",
                "WARNING_DAYS": "7",
            }
            script = ACTIONS / "stale-branch-cleanup/cleanup.py"
            fixture_path.write_text(json.dumps(fixture))
            subprocess.run(["python3", script], env=env, check=True, capture_output=True)
            self.assertFalse(mutations.exists())

            env["DRY_RUN"] = "false"
            subprocess.run(["python3", script], env=env, check=True, capture_output=True)
            writes = [json.loads(line) for line in mutations.read_text().splitlines()]
            self.assertEqual([entry["method"] for entry in writes], ["POST"])
            self.assertIn('"stale":', writes[0]["body"]["body"])
            self.assertNotIn('"protected":', writes[0]["body"]["body"])
            self.assertNotIn('"has-pr":', writes[0]["body"]["body"])

            fixture["issues"] = [
                {
                    "number": 1,
                    "user": {"login": "ci[bot]"},
                    "body": "<!-- personal-ci-stale-branches:"
                    + json.dumps({"stale": warning})
                    + " -->",
                }
            ]
            for changed in [True, False]:
                with self.subTest(tip_changed=changed):
                    fixture["current_sha"] = "new" if changed else "old"
                    fixture_path.write_text(json.dumps(fixture))
                    mutations.write_text("")
                    subprocess.run(["python3", script], env=env, check=True, capture_output=True)
                    writes = [json.loads(line) for line in mutations.read_text().splitlines()]
                    deletes = [entry for entry in writes if entry["method"] == "DELETE"]
                    self.assertEqual(len(deletes), 0 if changed else 1)
                    if deletes:
                        self.assertTrue(deletes[0]["endpoint"].endswith("/heads/stale"))
