name: Docker Lint
on:
  workflow_call:
permissions:
  contents: read
jobs:
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: hadolint
        uses: reviewdog/action-hadolint@2d0eb7c86a0ddd94eb625485f4cc2730e105edd8
        with:
          reporter: local
          filter_mode: nofilter
          fail_level: any
