name: GitHub Actions lint
on:
  workflow_call:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a
        with:
          reporter: local
          filter_mode: nofilter
          fail_level: any
      - uses: kellen-miller/ci/.github/actions/validate-workflow-security@8a6be24dc3b8595b2d838cdea638f9e6683fb4d0
