name: ShellCheck
on:
  workflow_call:
    inputs:
      pattern:
        description: Glob pattern for shell scripts to check
        required: false
        default: '*.sh'
        type: string
permissions:
  contents: read
jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: reviewdog/action-shellcheck@0722bbdb0d47f04c1b53b8734d2422ac63a45ec6
        with:
          reporter: local
          filter_mode: nofilter
          pattern: ${{ inputs.pattern }}
          fail_level: any
