name: YAML Lint
on:
  workflow_call:
permissions:
  contents: read
jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: yamllint
        uses: reviewdog/action-yamllint@de68272fdca5f2a961fb309e0d2e13c2eb186d9e
        with:
          reporter: local
          filter_mode: nofilter
          fail_level: any
